fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    remote_file: "git://github.com/lwf/puppet-remote_file.git"
  symlinks:
    datadog_agent: "#{source_dir}"
