fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.24.0"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "4.1.1"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.5.0"
    puppetserver_gem:
      repo: "git://github.com/puppetlabs/puppetlabs-puppetserver_gem.git"
      ref: "1.0.0"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
  forge_modules:
    yumrepo_core: "puppetlabs/yumrepo_core"
    powershell: "puppetlabs/powershell"
  symlinks:
    custom_datadog: "#{source_dir}/spec/custom_fixtures/custom_datadog"
    datadog_agent: "#{source_dir}"
