fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "6.0.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "6.0.0"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "7.0.1"
    puppetserver_gem:
      repo: "https://github.com/puppetlabs/puppetlabs-puppetserver_gem.git"
      ref: "1.1.1"
  forge_modules:
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.2.0"
    powershell:
      repo: "puppetlabs/powershell"
      ref: "4.1.0"
    zypprepo:
      repo: "puppet/zypprepo"
      ref: "5.0.0"
  symlinks:
    custom_datadog: "#{source_dir}/spec/custom_fixtures/custom_datadog"
    datadog_agent: "#{source_dir}"
