fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "2.2.0"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    remote_file: "git://github.com/lwf/puppet-remote_file.git"
  symlinks:
    custom_datadog: "#{source_dir}/spec/custom_fixtures/custom_datadog"
    datadog_agent: "#{source_dir}"
