fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    ruby: "https://github.com/puppetlabs/puppetlabs-ruby.git"
  symlinks:
    datadog_agent: "#{source_dir}"
