fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
  symlinks:
    datadog_agent: "#{source_dir}"
