---
fixtures:
  forge_modules:
    powershell: puppetlabs/powershell
    yumrepo_core: puppetlabs/yumrepo_core
    zypprepo: puppet/zypprepo
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt
    concat: https://github.com/puppetlabs/puppetlabs-concat
    puppetserver_gem: https://github.com/puppetlabs/puppetlabs-puppetserver_gem
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
  symlinks:
    custom_datadog: "#{source_dir}/spec/custom_fixtures/custom_datadog"
