---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: tests/environment/manifests
  modules_path: /tmp/modules
  require_puppet_repo: true
  require_chef_for_busser: false
  puppet_debug: true
  puppet_verbose: true
  custom_pre_apply_command: 'cp -r /tmp/modules/* /tmp/kitchen/modules/'

platforms:
  - name: centos7
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: tests/centos7/Vagrantfile
      provision: true

  - name: centos8
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: tests/centos8/Vagrantfile
      provision: true

  - name: ubuntu1604
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: tests/ubuntu1604/Vagrantfile
      provision: true

verifier:
  name: serverspec

suites:
  - name: dd-agent
    manifests: init.pp
    verifier:
      default_pattern: true
      env_vars:
        TARGET_HOST: 127.0.0.1
        TARGET_PORT: 2222
        LOGIN_USER: root
        LOGIN_PASSWORD: puppet
