language: ruby
before_install: rm -f Gemfile.lock
sudo: false
bundler_args: --full-index
cache: bundler
rvm:
  - 2.2.3
  - 2.3.1
  - 2.4.1
script:
  - bundle exec rake spec
  - bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.2.1" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
