language: ruby
before_install: rm -f Gemfile.lock
bundler_args: --full-index
cache: bundler
os:
  - windows
  - linux
rvm:
  - 2.1.9
  - 2.2.3
  - 2.3.6
  - 2.4.3
  - 2.6.3
script:
  - bundle exec rake test
env:
  global:
     - STRICT_VARIABLES=yes
  matrix:
    - PUPPET_VERSION="~> 4.6.2"
    - PUPPET_VERSION="~> 4.7.1"
    - PUPPET_VERSION="~> 4.8.2"
    - PUPPET_VERSION="~> 4.9.4"
    - PUPPET_VERSION="~> 4.10.9"
    - PUPPET_VERSION="~> 5.0.1"
    - PUPPET_VERSION="~> 5.1.0"
    - PUPPET_VERSION="~> 5.2.0"
    - PUPPET_VERSION="~> 5.3.3"
    - PUPPET_VERSION="~> 6.0.0"
    - PUPPET_VERSION="~> 6.5.0"
matrix:
  exclude:
    # Puppet 6 needs ruby 2.3+
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 6.0.0"
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 6.5.0"
    - rvm: 2.2.3
      env: PUPPET_VERSION="~> 6.0.0"
    - rvm: 2.2.3
      env: PUPPET_VERSION="~> 6.5.0"
