Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.provision "file", source: "../environment", destination: "$HOME/puppet"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y gem nano
    sudo gem install puppet r10k
    echo 'export PATH=$PATH:/usr/local/bin' | sudo tee /etc/bashrc
    cd /home/vagrant/puppet
    /usr/local/bin/r10k puppetfile install
  SHELL
end
