version: 2.1
orbs:
  win: circleci/windows@5.0.0
jobs:
  specs-ruby26-puppet734: &ubuntu2004-specs
    machine:
      image: ubuntu-2004:2024.08.1
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '7.34.0'
    steps:
    - checkout
    - run:
        name: Setup
        command: |
          # Needed to bundle install a puppet_litmus gem dependency
          sudo apt update -y
          sudo apt install -y libcurl4 curl libcurl4-openssl-dev
    - run:
        name: Install RVM
        command: |
          gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          \curl -sSL https://get.rvm.io | bash -s stable
    - run:
        name: Install Ruby version
        command: rvm install $RUBY_VERSION
    - run:
        name: Install bundler
        command: |
          rm Gemfile.lock && rvm $RUBY_VERSION --verbose do bundle config set path '.bundle'
          rvm $RUBY_VERSION --verbose do  gem install bundler:2.4.13
    - run:
        name: Install gem dependencies
        command: rvm $RUBY_VERSION --verbose do bundle install
    - run:
        name: Run tests
        command: rvm $RUBY_VERSION --verbose do bundle exec rake test

  specs-ruby27-puppet734:
    <<: *ubuntu2004-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.7.5'
      PUPPET_VERSION: '7.34.0'

  specs-ruby31-puppet734:
    <<: *ubuntu2004-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.1.6'
      PUPPET_VERSION: '7.34.0'

  specs-ruby32-puppet734:
    <<: *ubuntu2004-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.2.7'
      PUPPET_VERSION: '7.34.0'

  specs-ruby33-puppet734:
    <<: *ubuntu2004-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.3.7'
      PUPPET_VERSION: '7.34.0'

  specs-ruby34-puppet734:
    <<: *ubuntu2004-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.4.1'
      PUPPET_VERSION: '7.34.0'

  specs-ruby31-puppet810: &ubuntu2404-specs
    machine:
      image: ubuntu-2404:2024.08.1
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.1.6'
      PUPPET_VERSION: '8.10.0'
    steps:
    - checkout
    - run:
        name: Setup
        command: |
          # Needed to bundle install a puppet_litmus gem dependency
          sudo apt update -y
          sudo apt install -y libcurl4 curl libcurl4-openssl-dev
    - run:
        name: Install RVM
        command: |
          gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          \curl -sSL https://get.rvm.io | bash -s stable
    - run:
        name: Install Ruby version
        command: rvm install $RUBY_VERSION
    - run:
        name: Install bundler
        command: |
          rm Gemfile.lock && rvm $RUBY_VERSION --verbose do bundle config set path '.bundle'
          rvm $RUBY_VERSION --verbose do  gem install bundler:2.4.13
    - run:
        name: Install gem dependencies
        command: rvm $RUBY_VERSION --verbose do bundle install
    - run:
        name: Run tests
        command: rvm $RUBY_VERSION --verbose do bundle exec rake test

  specs-ruby32-puppet810:
    <<: *ubuntu2404-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.2.7'
      PUPPET_VERSION: '8.10.0'

  specs-ruby33-puppet810:
    <<: *ubuntu2404-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.3.7'
      PUPPET_VERSION: '8.10.0'

  specs-ruby34-puppet810:
    <<: *ubuntu2404-specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.4.1'
      PUPPET_VERSION: '8.10.0'

  # specs-ruby27-puppet79-windows:
  #   # &windows-specs
  #   executor:
  #     name: win/default
  #     shell: bash.exe
  #   steps:
  #   - checkout
  #   - run:
  #       name: Run tests
  #       command: |
  #         set -e
  #         choco install ruby --allow-downgrade -y --version=2.7.5.1 # Keep version in sync with next command!
  #         export PATH=/c/tools/ruby27/bin:$PATH # Make Ruby 2.7 take precedence over the pre-installed version
  #         ruby --version
  #         choco install msys2 -y
  #         ridk.cmd exec pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
  #         gem install bundler -v 2.4.13
  #         rm Gemfile.lock && bundle install --path .bundle
  #         bundle exec rake test
  #   environment:
  #     STRICT_VARIABLES: 'yes'
  #     #RUBY_VERSION hardcoded in install script
  #     PUPPET_VERSION: '7.9.0'

  verify-gemfile-lock-dependencies:
    machine:
      image: ubuntu-2404:2024.08.1
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.3.7'
    steps:
    - checkout
    - run:
        name: Setup
        command: |
          # Needed to bundle install a puppet_litmus gem dependency
          sudo apt update -y
          sudo apt install -y libcurl4 curl libcurl4-openssl-dev
    - run:
        name: Install RVM
        command: |
          gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          \curl -sSL https://get.rvm.io | bash -s stable
    - run:
        name: Install Ruby versions
        command: rvm install $RUBY_VERSION
    - run:
        name: Install bundler
        command: |
          rvm $RUBY_VERSION --verbose do bundle config set path '.bundle'
          rvm $RUBY_VERSION --verbose do  gem install bundler:2.4.13
    - run:
        name: Install gem dependencies
        command: rvm $RUBY_VERSION --verbose do bundle install
    - run:
        name: Run tests
        command: rvm $RUBY_VERSION --verbose do bundle exec rake test

  kitchen-tests:
    machine:
      image: ubuntu-2204:2024.08.1
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '3.4.1'
    steps:
    - checkout
    - run:
        name: Setup
        command: |
          # Needed to bundle install a puppet_litmus gem dependency
          sudo apt update -y
          sudo apt install -y libcurl4 curl libcurl4-openssl-dev      
    - run:
        name: Install RVM
        command: |
          gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          \curl -sSL https://get.rvm.io | bash -s stable
    - run:
        name: Install Ruby versions
        command: rvm install $RUBY_VERSION
    - run:
        name: Install bundler
        command: |
          rvm $RUBY_VERSION --verbose do bundle config set path '.bundle'
          rvm $RUBY_VERSION --verbose do  gem install bundler:2.4.13
    - run:
        name: Install gem dependencies
        command: rvm $RUBY_VERSION --verbose do bundle install
    - run:
        name: Execute Kitchen tests
        command: rvm $RUBY_VERSION --verbose do bundle exec rake circle
        no_output_timeout: "900s"

workflows:
  build_and_test:
    jobs:
    - specs-ruby26-puppet734
    # - specs-ruby27-puppet79-windows   # puppet_litmus requires a dependency "patron", which doesn't run on windows
    - specs-ruby27-puppet734
    - specs-ruby31-puppet734
    - specs-ruby32-puppet734
    - specs-ruby33-puppet734
    # - specs-ruby34-puppet734          # ruby v3.4 specs fail with `Puppet::Error: Cannot determine basic system flavour (Puppet::Error)`
    - specs-ruby31-puppet810
    - specs-ruby32-puppet810
    - specs-ruby33-puppet810
    # - specs-ruby34-puppet810
    - verify-gemfile-lock-dependencies
    - kitchen-tests
