version: 2
jobs:
  specs-ruby21-puppet46: &specs
    machine: true
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.1.9'
      PUPPET_VERSION: '4.6.2'
    steps:
      - checkout
      - run:
          name: Install Ruby version
          command: rvm install $RUBY_VERSION
      - run:
          name: Install bundler
          command: rvm $RUBY_VERSION --verbose do gem install bundler:1.17.3
      - run:
          name: Install gem dependencies
          command: rm Gemfile.lock && rvm $RUBY_VERSION --verbose do bundle install --path .bundle
      - run:
          name: Run tests
          command: rvm $RUBY_VERSION --verbose do bundle exec rake test

  specs-ruby21-puppet410:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.1.9'
      PUPPET_VERSION: '4.10.9'

  specs-ruby21-puppet50:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.1.9'
      PUPPET_VERSION: '5.0.1'

  specs-ruby21-puppet53:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.1.9'
      PUPPET_VERSION: '5.3.3'

  # Puppet 6 depends on ruby >= 2.3
  #specs-ruby21-puppet60
  #specs-ruby21-puppet65

  specs-ruby22-puppet46:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.2.3'
      PUPPET_VERSION: '4.6.2'

  specs-ruby22-puppet410:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.2.3'
      PUPPET_VERSION: '4.10.9'

  specs-ruby22-puppet50:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.2.3'
      PUPPET_VERSION: '5.0.1'

  specs-ruby22-puppet53:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.2.3'
      PUPPET_VERSION: '5.3.3'

  # Puppet 6 depends on ruby >= 2.3
  #specs-ruby22-puppet60
  #specs-ruby22-puppet65

  specs-ruby23-puppet46:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.3.6'
      PUPPET_VERSION: '4.6.2'

  specs-ruby23-puppet410:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.3.6'
      PUPPET_VERSION: '4.10.9'

  specs-ruby23-puppet50:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.3.6'
      PUPPET_VERSION: '5.0.1'

  specs-ruby23-puppet53:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.3.6'
      PUPPET_VERSION: '5.3.3'

  specs-ruby23-puppet60:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.3.6'
      PUPPET_VERSION: '6.0.0'

  specs-ruby23-puppet65:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.3.6'
      PUPPET_VERSION: '6.5.0'

  specs-ruby24-puppet46:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.4.3'
      PUPPET_VERSION: '4.6.2'

  specs-ruby24-puppet410:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.4.3'
      PUPPET_VERSION: '4.10.9'

  specs-ruby24-puppet50:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.4.3'
      PUPPET_VERSION: '5.0.1'

  specs-ruby24-puppet53:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.4.3'
      PUPPET_VERSION: '5.3.3'

  specs-ruby24-puppet60:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.4.3'
      PUPPET_VERSION: '6.0.0'

  specs-ruby24-puppet65:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.4.3'
      PUPPET_VERSION: '6.5.0'

  specs-ruby26-puppet46:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '4.6.2'

  specs-ruby26-puppet410:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '4.10.9'

  specs-ruby26-puppet50:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '5.0.1'

  specs-ruby26-puppet53:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '5.3.3'

  specs-ruby26-puppet60:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '6.0.0'

  specs-ruby26-puppet65:
    <<: *specs
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
      PUPPET_VERSION: '6.5.0'

  verify-gemfile-lock-dependencies:
    machine: true
    environment:
      STRICT_VARIABLES: 'yes'
      RUBY_VERSION: '2.6.3'
    steps:
      - checkout
      - run:
          name: Install Ruby versions
          command: rvm install $RUBY_VERSION
      - run:
          name: Install bundler
          command: rvm $RUBY_VERSION --verbose do gem install bundler:1.17.3
      - run:
          name: Install gem dependencies
          command: rvm $RUBY_VERSION --verbose do bundle install --path .bundle
      - run:
          name: Run tests
          command: rvm $RUBY_VERSION --verbose do bundle exec rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      #- specs-ruby25-puppet410-windows
      #- specs-ruby26-puppet65-windows
      - specs-ruby21-puppet46
      - specs-ruby21-puppet410
      - specs-ruby21-puppet50
      - specs-ruby21-puppet53
      - specs-ruby22-puppet46
      - specs-ruby22-puppet410
      - specs-ruby22-puppet50
      - specs-ruby22-puppet53
      - specs-ruby23-puppet46
      - specs-ruby23-puppet410
      - specs-ruby23-puppet50
      - specs-ruby23-puppet53
      - specs-ruby23-puppet60
      - specs-ruby23-puppet65
      - specs-ruby24-puppet46
      - specs-ruby24-puppet410
      - specs-ruby24-puppet50
      - specs-ruby24-puppet53
      - specs-ruby24-puppet60
      - specs-ruby24-puppet65
      - specs-ruby26-puppet46
      - specs-ruby26-puppet410
      - specs-ruby26-puppet50
      - specs-ruby26-puppet53
      - specs-ruby26-puppet60
      - specs-ruby26-puppet65
      - verify-gemfile-lock-dependencies
