Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.provision "file", source: "../../../environments/etc", destination: "$HOME/puppet"
  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
    dnf install -y puppet
    systemctl start puppet
    systemctl enable puppet

    /opt/puppetlabs/puppet/bin/gem install r10k -v 2.6.7
    cd /home/vagrant/puppet
    sudo su vagrant -c "/opt/puppetlabs/puppet/bin/r10k puppetfile install --moduledir=/tmp/modules"
  SHELL
end
