Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.provision "file", source: "../../environments/etc", destination: "$HOME/puppet"
  config.vm.synced_folder "../../", "/puppet-datadog-agent"
  config.vm.provision "shell", inline: <<-SHELL
    #install puppet 6
    dnf install -y https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
    dnf install -y puppet

    # install modules
    cd /home/vagrant/puppet
    gem install r10k -v 2.6.7
    r10k puppetfile install --moduledir=/home/vagrant/puppet/modules

    # link local module
    ln -s /puppet-datadog-agent /home/vagrant/puppet/modules/datadog_agent
  SHELL
end
