Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.provision "file", source: "../../../tests/environment", destination: "$HOME/puppet"
  config.vm.provision "shell", inline: <<-SHELL
    rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
    yum install -y puppet
    systemctl start puppet
    systemctl enable puppet

    gem install r10k -v 2.6.7
    cd /home/vagrant/puppet
    sudo su vagrant -c "/usr/local/bin/r10k puppetfile install --moduledir=/tmp/modules"
  SHELL
end
