# Track control branch and fall-back to master if no matching branch.
mod 'datadog_agent', :local => true
mod 'puppetlabs-apt', '2.4.0'
mod 'puppetlabs-concat', '4.0.0'
mod 'puppetlabs-puppetserver_gem', '1.0.0'
mod 'puppetlabs-ruby', '1.0.0'
mod 'puppetlabs-stdlib', '4.25.0'
mod 'puppetlabs-powershell', '2.3.0'
mod 'puppetlabs-yumrepo_core', '1.0.3'
mod 'puppet-zypprepo', '3.1.0'
